# ============================================================
# visualize_recent_graphs.py
#
# Visualizes the NEW graphs generated by:
#     integrate_and_rebuild.py
#
# It preserves the OLD visualization style:
#
#   1. 49-Dimensional Node Feature Graph
#   2. Volleyball Spatial Graph
#
# Source:
#     output_recent/graphs/
#
# Output:
#     output_recent/graph_images/
#
# IMPORTANT FEATURE LAYOUT:
#
#   0:2    -> node type
#   2:4    -> spatial X,Y
#   4:6    -> velocity
#   6:8    -> team
#   8:42   -> 17 keypoints = 34 pose features
#   42     -> pose available
#   43     -> pose confidence
#   44:49  -> remaining court/features
#
# ============================================================

from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import torch


# ============================================================
# CONSTANTS
# ============================================================

PLAYER_NODE_TYPE = 0
BALL_NODE_TYPE = 1

PLAYER_PLAYER_EDGE_TYPE = 0
PLAYER_BALL_EDGE_TYPE = 1

FEATURE_DIMENSION = 49

SPATIAL_X_INDEX = 2
SPATIAL_Y_INDEX = 3

POSE_START = 8
POSE_END = 42


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent

GRAPH_DIR = (
    ROOT
    / "output_recent"
    / "graphs"
)

OUTPUT_DIR = (
    ROOT
    / "output_recent"
    / "graph_images"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# LOAD GRAPH
# ============================================================

def load_graph(graph_path):
    """
    Load a graph saved by integrate_and_rebuild.py.

    The .pt file contains:

        {
            "frame_id": ...,
            "graph": graph,
            "gat_node_embeddings": ...,
            "hrn_node_embeddings": ...,
            ...
        }
    """

    data = torch.load(
        graph_path,
        map_location="cpu",
        weights_only=False
    )

    if isinstance(data, dict):

        if "graph" not in data:

            raise RuntimeError(
                f"'graph' not found inside:\n{graph_path}"
            )

        return data["graph"]

    return data


# ============================================================
# TORCH -> NUMPY
# ============================================================

def to_numpy(value):

    if torch.is_tensor(value):

        return (
            value
            .detach()
            .cpu()
            .numpy()
        )

    return np.asarray(value)


# ============================================================
# GET MF3 PLAYER IDS
# ============================================================

def get_player_ids(
    graph,
    player_indices
):
    """
    Retrieve MF3 player IDs stored on the graph.

    graph.player_ids corresponds to PLAYER NODES only.
    """

    player_ids = getattr(
        graph,
        "player_ids",
        None
    )

    # --------------------------------------------------------
    # If IDs are not stored, fall back to node indices.
    # --------------------------------------------------------

    if player_ids is None:

        return [
            int(index)
            for index in player_indices
        ]

    # --------------------------------------------------------
    # Tensor -> numpy/list
    # --------------------------------------------------------

    if torch.is_tensor(player_ids):

        player_ids = (
            player_ids
            .detach()
            .cpu()
            .numpy()
            .reshape(-1)
            .tolist()
        )

    else:

        player_ids = list(
            player_ids
        )

    return player_ids[
        :len(player_indices)
    ]


# ============================================================
# POSE STATISTICS
# ============================================================

def calculate_pose_statistics(graph):

    features = to_numpy(
        graph.x
    )

    node_type = to_numpy(
        graph.node_type
    ).reshape(-1)

    # --------------------------------------------------------
    # Player nodes only
    # --------------------------------------------------------

    player_indices = np.where(
        node_type == PLAYER_NODE_TYPE
    )[0]

    if len(player_indices) == 0:

        return {
            "players": 0,
            "pose_players": 0,
            "pose_percentage": 0.0,
            "pose_nonzero": 0,
            "pose_total": 0,
        }

    # --------------------------------------------------------
    # Pose block = features 8:42
    # --------------------------------------------------------

    pose = features[
        player_indices,
        POSE_START:POSE_END
    ]

    # --------------------------------------------------------
    # Player considered to have pose if
    # any of the 34 values is non-zero.
    # --------------------------------------------------------

    populated = (
        np.count_nonzero(
            pose,
            axis=1
        ) > 0
    )

    pose_players = int(
        populated.sum()
    )

    total_players = len(
        player_indices
    )

    return {
        "players":
            total_players,

        "pose_players":
            pose_players,

        "pose_percentage":
            (
                100.0
                * pose_players
                / total_players
            ),

        "pose_nonzero":
            int(
                np.count_nonzero(
                    pose
                )
            ),

        "pose_total":
            int(
                pose.size
            ),
    }


# ============================================================
# 49-D FEATURE HEATMAP
# ============================================================

def visualize_feature_graph(
    graph,
    frame_id
):
    """
    Generate the OLD-style 49-D feature heatmap.

    Rows:
        graph nodes

    Columns:
        49 node features

    IMPORTANT:
        This plots the actual graph.x values.
        Nothing is generated artificially.
    """

    features = to_numpy(
        graph.x
    )

    # --------------------------------------------------------
    # Validate dimensions
    # --------------------------------------------------------

    if features.ndim != 2:

        raise RuntimeError(
            f"graph.x must be 2-D. "
            f"Got {features.shape}"
        )

    if features.shape[1] != FEATURE_DIMENSION:

        raise RuntimeError(
            f"Expected 49-D features. "
            f"Got {features.shape[1]}"
        )

    # --------------------------------------------------------
    # Create figure
    # --------------------------------------------------------

    plt.figure(
        figsize=(14, 6)
    )

    # --------------------------------------------------------
    # OLD heatmap style
    # --------------------------------------------------------

    plt.imshow(
        features,
        aspect="auto"
    )

    plt.xlabel(
        "Feature Index"
    )

    plt.ylabel(
        "Node Index"
    )

    plt.title(
        f"49-Dimensional Node Feature Graph - Frame {frame_id}"
    )

    plt.colorbar(
        label="Normalized Feature Value"
    )

    plt.tight_layout()

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output_path = (
        OUTPUT_DIR
        / f"frame_{int(frame_id):04d}_features.png"
    )

    plt.savefig(
        output_path,
        dpi=150,
        bbox_inches="tight"
    )

    plt.close()

    print(
        f"  Saved features: "
        f"{output_path.name}"
    )


# ============================================================
# VOLLEYBALL SPATIAL GRAPH
# ============================================================

def visualize_graph(
    graph,
    frame_id
):
    """
    Generate the OLD-style volleyball spatial graph.

    Spatial coordinates come from:

        graph.x[:, 2] -> X
        graph.x[:, 3] -> Y

    NOT:

        graph.x[:, 0]
        graph.x[:, 1]

    because 0:2 are node-type features.
    """

    features = to_numpy(
        graph.x
    )

    edge_index = to_numpy(
        graph.edge_index
    )

    edge_type = to_numpy(
        graph.edge_type
    ).reshape(-1)

    node_type = to_numpy(
        graph.node_type
    ).reshape(-1)

    # --------------------------------------------------------
    # Team
    # --------------------------------------------------------

    node_team = getattr(
        graph,
        "node_team",
        None
    )

    if node_team is not None:

        node_team = to_numpy(
            node_team
        ).reshape(-1)

    # ========================================================
    # CRITICAL:
    #
    # Feature 0 = node type
    # Feature 1 = node type
    #
    # Feature 2 = spatial X
    # Feature 3 = spatial Y
    # ========================================================

    x_positions = features[
        :,
        SPATIAL_X_INDEX
    ]

    y_positions = features[
        :,
        SPATIAL_Y_INDEX
    ]

    # --------------------------------------------------------
    # Player / ball nodes
    # --------------------------------------------------------

    player_indices = np.where(
        node_type == PLAYER_NODE_TYPE
    )[0]

    ball_indices = np.where(
        node_type == BALL_NODE_TYPE
    )[0]

    # ========================================================
    # FIGURE
    # ========================================================

    plt.figure(
        figsize=(12, 7)
    )

    # ========================================================
    # EDGES
    # ========================================================

    for edge_number in range(
        edge_index.shape[1]
    ):

        source = int(
            edge_index[
                0,
                edge_number
            ]
        )

        target = int(
            edge_index[
                1,
                edge_number
            ]
        )

        # ----------------------------------------------------
        # Player-player
        # ----------------------------------------------------

        if edge_type[edge_number] == (
            PLAYER_PLAYER_EDGE_TYPE
        ):

            linestyle = "-"
            alpha = 0.25

        # ----------------------------------------------------
        # Player-ball
        # ----------------------------------------------------

        elif edge_type[edge_number] == (
            PLAYER_BALL_EDGE_TYPE
        ):

            linestyle = "--"
            alpha = 0.55

        # ----------------------------------------------------
        # Unknown edge type
        # ----------------------------------------------------

        else:

            linestyle = ":"
            alpha = 0.20

        plt.plot(
            [
                x_positions[source],
                x_positions[target]
            ],
            [
                y_positions[source],
                y_positions[target]
            ],
            linestyle=linestyle,
            alpha=alpha
        )

    # ========================================================
    # PLAYERS
    # ========================================================

    if len(player_indices) > 0:

        # ----------------------------------------------------
        # Team colors
        # ----------------------------------------------------

        if node_team is not None:

            player_colors = []

            for node_index in player_indices:

                team = node_team[
                    node_index
                ]

                if team == 0:

                    player_colors.append(
                        "tab:blue"
                    )

                elif team == 1:

                    player_colors.append(
                        "tab:orange"
                    )

                else:

                    player_colors.append(
                        "gray"
                    )

        else:

            player_colors = None

        plt.scatter(
            x_positions[
                player_indices
            ],
            y_positions[
                player_indices
            ],
            s=100,
            c=player_colors,
            label="Player"
        )

    # ========================================================
    # BALL
    # ========================================================

    if len(ball_indices) > 0:

        plt.scatter(
            x_positions[
                ball_indices
            ],
            y_positions[
                ball_indices
            ],
            s=150,
            color="red",
            label="Ball"
        )

    # ========================================================
    # MF3 PLAYER IDS
    # ========================================================

    player_ids = get_player_ids(
        graph,
        player_indices
    )

    for node_index, player_id in zip(
        player_indices,
        player_ids
    ):

        plt.annotate(
            f"P{player_id}",
            (
                x_positions[
                    node_index
                ],
                y_positions[
                    node_index
                ]
            ),
            xytext=(5, 5),
            textcoords="offset points"
        )

    # ========================================================
    # FORMAT
    # ========================================================

    plt.xlabel(
        "Normalized X"
    )

    plt.ylabel(
        "Normalized Y"
    )

    plt.title(
        f"Volleyball Graph - Frame {frame_id}"
    )

    plt.xlim(
        0,
        1
    )

    # Image coordinates:
    # Y increases downward.
    plt.ylim(
        1,
        0
    )

    plt.legend()

    plt.grid(
        alpha=0.2
    )

    plt.tight_layout()

    # ========================================================
    # SAVE
    # ========================================================

    output_path = (
        OUTPUT_DIR
        / f"frame_{int(frame_id):04d}_graph.png"
    )

    plt.savefig(
        output_path,
        dpi=150,
        bbox_inches="tight"
    )

    plt.close()

    print(
        f"  Saved graph:    "
        f"{output_path.name}"
    )


# ============================================================
# PROCESS ONE FRAME
# ============================================================

def process_frame(
    graph_path
):

    # --------------------------------------------------------
    # Extract frame ID
    # --------------------------------------------------------

    frame_id = int(
        graph_path.stem.split("_")[-1]
    )

    print()
    print(
        f"Processing Frame {frame_id}"
    )

    # --------------------------------------------------------
    # Load actual graph
    # --------------------------------------------------------

    graph = load_graph(
        graph_path
    )

    # --------------------------------------------------------
    # Validate graph.x
    # --------------------------------------------------------

    features = to_numpy(
        graph.x
    )

    if features.ndim != 2:

        raise RuntimeError(
            f"Invalid graph.x shape: "
            f"{features.shape}"
        )

    if features.shape[1] != 49:

        raise RuntimeError(
            f"Expected [nodes, 49]. "
            f"Got {features.shape}"
        )

    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    stats = calculate_pose_statistics(
        graph
    )

    print(
        f"  Nodes: {features.shape[0]}"
    )

    print(
        f"  Edges: "
        f"{graph.edge_index.shape[1]}"
    )

    print(
        f"  Features: "
        f"{features.shape}"
    )

    print(
        f"  Pose: "
        f"{stats['pose_players']}/"
        f"{stats['players']} "
        f"({stats['pose_percentage']:.1f}%)"
    )

    print(
        f"  Pose non-zero: "
        f"{stats['pose_nonzero']}/"
        f"{stats['pose_total']}"
    )

    # --------------------------------------------------------
    # Generate OLD visualizations
    # --------------------------------------------------------

    visualize_feature_graph(
        graph,
        frame_id
    )

    visualize_graph(
        graph,
        frame_id
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print(
        "=" * 75
    )

    print(
        "GENERATING OLD-STYLE VISUALIZATIONS "
        "FOR ALL RECENT GRAPHS"
    )

    print(
        "=" * 75
    )

    print()
    print(
        "Input:"
    )

    print(
        GRAPH_DIR
    )

    print()
    print(
        "Output:"
    )

    print(
        OUTPUT_DIR
    )

    # ========================================================
    # FIND GRAPH FILES
    # ========================================================

    graph_files = sorted(
        GRAPH_DIR.glob(
            "graph_frame_*.pt"
        )
    )

    if not graph_files:

        raise FileNotFoundError(
            "\nNo graph files found.\n\n"
            f"Expected:\n{GRAPH_DIR}\n\n"
            "Run integrate_and_rebuild.py first."
        )

    print()
    print(
        f"Graphs found: "
        f"{len(graph_files)}"
    )

    print()

    # ========================================================
    # PROCESS
    # ========================================================

    successful = 0
    failed = 0

    for index, graph_path in enumerate(
        graph_files,
        start=1
    ):

        try:

            frame_id = int(
                graph_path.stem.split("_")[-1]
            )

            print(
                f"[{index}/{len(graph_files)}] "
                f"Frame {frame_id}"
            )

            process_frame(
                graph_path
            )

            successful += 1

        except Exception as exc:

            failed += 1

            print()
            print(
                f"  ✗ Frame failed:"
            )

            print(
                f"    {type(exc).__name__}: "
                f"{exc}"
            )

    # ========================================================
    # SUMMARY
    # ========================================================

    print()
    print(
        "=" * 75
    )

    print(
        "VISUALIZATION COMPLETE"
    )

    print(
        "=" * 75
    )

    print()
    print(
        f"Successful: {successful}"
    )

    print(
        f"Failed:     {failed}"
    )

    print()
    print(
        "Output directory:"
    )

    print(
        OUTPUT_DIR
    )

    print()
    print(
        "For every successful frame:"
    )

    print(
        "  frame_XXXX_features.png"
    )

    print(
        "  frame_XXXX_graph.png"
    )

    print()
    print(
        "Feature layout:"
    )

    print(
        "  0:2   node type"
    )

    print(
        "  2:4   spatial X,Y"
    )

    print(
        "  4:6   velocity"
    )

    print(
        "  6:8   team"
    )

    print(
        "  8:42  34-D latest pose"
    )

    print(
        "  42    pose availability"
    )

    print(
        "  43    pose confidence"
    )

    print(
        "  44:49 remaining features"
    )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    main()