"""Project-wide constants used across the tracking pipeline."""

DEFAULT_FPS = 30.0
DEFAULT_MAX_DISTANCE = 200.0
DEFAULT_MIN_DURATION_SEC = 1.0
DEFAULT_MAX_X_DISPLACEMENT = 20.0
DEFAULT_MIN_Y_DISPLACEMENT = 50.0
DEFAULT_BOUNCE_FRAMES = 10

DEFAULT_INPUT_WIDTH = 512
DEFAULT_INPUT_HEIGHT = 288
DEFAULT_HEATMAP_THRESHOLD = 0.5
DEFAULT_DETECTION_BOX_RADIUS = 20
DEFAULT_EXTEND_SECONDS = 1.0
DEFAULT_FADE_DURATION = 0.5

COURT_LENGTH_M = 18.0
COURT_WIDTH_M = 9.0
NET_HEIGHT_M = 2.43
DEFAULT_NET_Y_THRESHOLD = 200

DEFAULT_IMAGE_WIDTH = 1280
DEFAULT_IMAGE_HEIGHT = 720

DEFAULT_CROP_ASPECT_RATIO = 9 / 16
DEFAULT_SMOOTH_WINDOW = 15
